#!/bin/bash

if [ "$#" -ne 2 ] ; then
    echo "Generate a number of router keys"
    echo "Usage: '$0 <number> <output-dir>'"
    exit 1
fi

if [ ! -d $2 ]; then
    echo "Directory $2 does not exist"
    exit 1
fi

key=1
outdir=${2%/}

for (( i=0; i<$1; ))
do
    if [[ -e "$outdir/$key.der" || -e "$outdir/$key.pem" ]]
    then
        echo "Keys for $key already exists, skipping..."
    else
        echo "Generating $key.der, $key.pem and $key.cert"
        openssl ecparam -name prime256v1 -genkey -out $outdir/$key.pem
        openssl ec -in $outdir/$key.pem -outform der -out $outdir/$key.der

        # Create Certificate Request
        openssl req -new -batch -config key.conf -key $outdir/$key.pem -out $outdir/$key.csr
        sub=$(openssl req -in $outdir/$key.csr -text | ./get-ski.py)
        echo "Subject='$sub'"
        openssl req -new -batch -subj /CN=$sub -config key.conf -key $outdir/$key.pem -out $outdir/$key.csr

        # Create Certificate
        echo "Create Certificate for $key"
        openssl x509 -sha256 -extfile key.conf -extensions bgpsec_router_ext -set_serial 20140220001 -in $outdir/$key.csr -outform DER -out $outdir/$key.cert -req -signkey $outdir/$key.pem -days 365

        # Remove certificate request
        rm -f $outdir/$key.csr
        
        i=$(( $i + 1 ))
    fi
    key=$(( $key + 1 ))
done
