#!/bin/bash

if [[ "$#" -ne 2 ]]; then
    echo "Sort keys in sub directories"
    echo "Usage: '$0 TARGET_DIR FILE_EXT'"
    exit 1
fi

if [ ! -d $1 ]; then
    echo "Directory $1 does not exist"
    exit 1
fi

cd $1
ext=$2

mkdir {0..9} {A..F} 2> /dev/null

for d in {0..9}
do
    mv $d*.$ext $d/ 2> /dev/null
done

for d in {A..F}
do
    mv $d*.$ext $d/ 2> /dev/null
done
